### ISSUE TITLE
[BUG] - Component met value attribuut via setAttribute leegmaken triggert geen change event

### ISSUE THREAD

**Issue by SBylemans** [milieuinfo/webcomponent-vl-ui-input-field#48]
**Omschrijf het probleem**
We initialiseren de component met een `.value` attribuut. Bij het leegmaken van de value van de component wordt er geen change event uitgestuurd.

**Hoe te reproduceren**
Stappen om het probleem te reproduceren en indien mogelijks een code snippet:

```
<input is="vl-input-field" .value=${"test"} @change="${this.change}></input>"

function change(e) {
    this.value = e.detail.value;
}
```
leegmaken van inputfield triggert niet de change event listener.

**Gewenst gedrag**
Wel een change event

**Screenshots**
Indien mogelijk, voeg hier screenshots/logs/videos toe

**Omgeving (gelieve aan te vullen):**
 - Safari
 - Versie [vb. 22]
 - Versie component [vb. 1.0.14]

**Extra info**

**Comment by coemans** [comment]
@SBylemans ik kan het probleem niet reproduceren op de vl-ui-input-field demo pagina met onderstaande code:

```JavaScript
document.querySelector('input').addEventListener('change', () => { console.log('change event triggered'); });
```

Let op, een change event wordt maar gestuurd wanneer er interactie geweest is met de gebruiker, niet wanneer de value programmatisch gezet wordt. Dit is standaard gedrag van een HTMLInputElement.

**Comment by SBylemans** [comment]
@coemans Heb het eens met Zjaodi overlopen en het komt doordat we het als attribuut zetten en niet als property. Is dit gewenst gedrag?

**Comment by coemans** [comment]
Bij het programmatisch zetten van een input value ben je zelf verantwoordelijk voor het sturen van een change event. Omdat er ook bij een HTMLInputElement bij het programmatisch zetten van de value geen change event gestuurd wordt, is het gedrag gewenst.

**Comment by SBylemans** [comment]
@coemans Ik zet het nu ook als value programmatisch en op een later tijdstip maar als property nu en dat lijkt dan wel te werken. Dit lijkt me toch niet correct? En bij de checkbox probeer ik dan de checked property te zetten, en dat werkt niet. Daar moet ik het dan wel als attribuut zetten....

**Comment by coemans** [comment]
@SBylemans de vl-ui-input-field heeft geen eigen code implementatie dus zou identiek moeten werken aan het input element van HTML. Kan je een falende test toevoegen op een branch dat het probleem aantoont? Indien de bug dan niet reproduceerbaar is met een native input element is er inderdaad een probleem, maar anders is het gewenst gedrag.

De vl-ui-checkbox is geen native webcomponent, dus die kan uitgebreid worden met een checked setter indien nodig. Hiervoor kan een issue of PR aangemaakt worden.

**Comment by coemans** [comment]
Samen met @SBylemans onderzocht en het is effectief een native input probleem:

``` HTML
<input id="test" type="text"/>
```

``` JavaScript
const input = document.querySelector('#test');
input.value = 'Programmatically set value';
input.addEventListener('change', () => { console.log('change event was triggered'); });
```

Vervolgens het input element manueel leegmaken zorgt voor een change event. Maar wanneer we onderstaande code uitvoeren, gebeurt er geen change event:

```JavaScript
const input = document.querySelector('#test');
input.setAttribute('value', 'Programmatically set value');
input.addEventListener('change', () => { console.log('change event was not triggered'); });
```

Het gedrag van de vl-ui-input-field is identiek aan het gedrag van een native HTML input element. Dit gedrag is op zijn minst vreemd, dus ik zal eens zoeken of dit ergens gemeld kan worden. Het lokaal fixen en afwijken van het native input gedrag zorgt misschien vroeg of laat voor andere problemen en is daarom af te raden.

Voor de ontbrekende value, checked setter en getter functionaliteit bij vl-ui-checkbox zal ik een nieuw issue aanmaken.
